# Generated by Django 6.1 on 2026-08-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ciclo', models.CharField(choices=[('PRIMAVERA', 'Primavera'), ('OTONO', 'Otoño')], max_length=20)),
                ('anio', models.PositiveSmallIntegerField()),
                ('resumen', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('CERRADA', 'Cerrada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20)),
                ('destacada', models.BooleanField(default=False)),
                ('fuente_oficial_url', models.URLField(blank=True)),
                ('documento_oficial', models.FileField(blank=True, null=True, upload_to='convocatorias/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-anio', 'ciclo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='IES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=100)),
                ('estado_region', models.CharField(blank=True, max_length=150)),
                ('sitio_web', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IES',
                'verbose_name_plural': 'IES',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de movilidad',
                'verbose_name_plural': 'Tipos de movilidad',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FechaImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('es_fecha_limite', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_importantes', to='convocatorias.convocatoria')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='convocatorias.convocatoria')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='tipo_movilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias', to='convocatorias.tipomovilidad'),
        ),
        migrations.CreateModel(
            name='ConvocatoriaIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to='convocatorias.convocatoria')),
                ('ies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias', to='convocatorias.ies')),
            ],
            options={
                'ordering': ['orden', 'ies__nombre'],
                'constraints': [models.UniqueConstraint(fields=('convocatoria', 'ies'), name='unique_ies_por_convocatoria')],
            },
        ),
    ]
