# Generated by Django 6.1 on 2026-08-25 18:13

from django.db import migrations


def cargar_tipos_movilidad(apps, schema_editor):
    TipoMovilidad = apps.get_model(
        "convocatorias",
        "TipoMovilidad"
    )

    tipos = [
        {
            "nombre": "Intrainstitucional",
            "descripcion": (
                "Movilidad académica entre espacios académicos "
                "de la Universidad Autónoma del Estado de México."
            ),
            "orden": 1,
        },
        {
            "nombre": "Nacional saliente",
            "descripcion": (
                "Movilidad académica de estudiantes UAEMéx "
                "hacia instituciones de educación superior nacionales."
            ),
            "orden": 2,
        },
        {
            "nombre": "Internacional saliente",
            "descripcion": (
                "Movilidad académica de estudiantes UAEMéx "
                "hacia instituciones de educación superior extranjeras."
            ),
            "orden": 3,
        },
    ]

    for tipo in tipos:
        TipoMovilidad.objects.get_or_create(
            nombre=tipo["nombre"],
            defaults={
                "descripcion": tipo["descripcion"],
                "orden": tipo["orden"],
                "activo": True,
            },
        )


def eliminar_tipos_movilidad(apps, schema_editor):
    TipoMovilidad = apps.get_model(
        "convocatorias",
        "TipoMovilidad"
    )

    TipoMovilidad.objects.filter(
        nombre__in=[
            "Intrainstitucional",
            "Nacional saliente",
            "Internacional saliente",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            cargar_tipos_movilidad,
            eliminar_tipos_movilidad,
        ),
    ]