# Generated by Django 6.1 on 2026-09-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_cargar_tipos_movilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoriaies',
            options={'ordering': ['orden', 'ies__nombre'], 'verbose_name_plural': 'convocatorias de IES'},
        ),
    ]
