# Generated by Django 6.1 on 2026-08-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de FAQ',
                'verbose_name_plural': 'Categorías de FAQ',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('fuente_oficial_url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='publicaciones.categoriafaq')),
                ('tipo_movilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_frecuentes', to='convocatorias.tipomovilidad')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['categoria__orden', 'orden', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('INFORMACION', 'Información'), ('AVISO', 'Aviso'), ('URGENTE', 'Urgente')], default='INFORMACION', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=False)),
                ('destacada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='convocatorias.convocatoria')),
                ('tipo_movilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='convocatorias.tipomovilidad')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-creado_en'],
            },
        ),
    ]
