# Generated by Django 6.1 on 2026-09-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0003_alter_convocatoriaies_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('etapa', models.CharField(choices=[('ANTES', 'Antes de la movilidad'), ('DURANTE', 'Durante la movilidad'), ('DESPUES', 'Después de la movilidad')], max_length=20)),
                ('responsable', models.CharField(choices=[('ALUMNO', 'Alumno'), ('RESPONSABLE_MOVILIDAD', 'Responsable de movilidad'), ('ESPACIO_ACADEMICO', 'Espacio académico'), ('DAAE', 'DAAE'), ('IES_DESTINO', 'IES destino'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('OTRO', 'Otro')], max_length=30)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('estado_expediente', models.CharField(choices=[('INICIADO', 'Iniciado'), ('INTEGRANDO_EXPEDIENTE', 'Integrando expediente'), ('EN_REVISION', 'En revisión'), ('ENVIADO_DAAE', 'Enviado a DAAE'), ('POSTULACION_IES', 'Postulación ante IES'), ('PREPARACION_MOVILIDAD', 'Preparación de movilidad'), ('EN_MOVILIDAD', 'En movilidad'), ('HOMOLOGACION', 'En proceso de homologación'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('tipo_movilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_proceso', to='convocatorias.tipomovilidad')),
            ],
            options={
                'verbose_name': 'Actividad del proceso',
                'verbose_name_plural': 'Actividades del proceso',
                'ordering': ['tipo_movilidad', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ActividadExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('EN_REVISION', 'En revisión'), ('COMPLETADA', 'Completada'), ('REQUIERE_CORRECCION', 'Requiere corrección'), ('NO_APLICA', 'No aplica'), ('NO_REGISTRADA', 'No registrada en el sistema')], default='PENDIENTE', max_length=30)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='expedientes.actividadproceso')),
            ],
            options={
                'verbose_name': 'Actividad del expediente',
                'verbose_name_plural': 'Actividades del expediente',
                'ordering': ['actividad_proceso__orden'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('INTEGRANDO_EXPEDIENTE', 'Integrando expediente'), ('EN_REVISION', 'En revisión'), ('ENVIADO_DAAE', 'Enviado a DAAE'), ('POSTULACION_IES', 'Postulación ante IES'), ('PREPARACION_MOVILIDAD', 'Preparación de movilidad'), ('EN_MOVILIDAD', 'En movilidad'), ('HOMOLOGACION', 'En proceso de homologación'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=30)),
                ('tipo_alta', models.CharField(choices=[('NORMAL', 'Alta normal'), ('EXCEPCIONAL', 'Expediente recibido en curso')], default='NORMAL', max_length=20)),
                ('estado_inicial', models.CharField(choices=[('INICIADO', 'Iniciado'), ('INTEGRANDO_EXPEDIENTE', 'Integrando expediente'), ('EN_REVISION', 'En revisión'), ('ENVIADO_DAAE', 'Enviado a DAAE'), ('POSTULACION_IES', 'Postulación ante IES'), ('PREPARACION_MOVILIDAD', 'Preparación de movilidad'), ('EN_MOVILIDAD', 'En movilidad'), ('HOMOLOGACION', 'En proceso de homologación'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=30)),
                ('origen', models.CharField(choices=[('NUEVO', 'Nuevo'), ('GESTION_ANTERIOR', 'Recibido de gestión anterior'), ('REGISTRO_PREVIO', 'Migrado de registro previo'), ('OTRO', 'Otro')], default='NUEVO', max_length=30)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion_area', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_alta_excepcional', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_movilidad', to=settings.AUTH_USER_MODEL)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='convocatorias.convocatoria')),
                ('ies_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='convocatorias.convocatoriaies')),
            ],
            options={
                'verbose_name': 'Expediente de movilidad',
                'verbose_name_plural': 'Expedientes de movilidad',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='movilidad/expedientes/')),
                ('estado', models.CharField(choices=[('CARGADO', 'Cargado'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('REQUIERE_CORRECCION', 'Requiere corrección'), ('RECHAZADO', 'Rechazado')], default='CARGADO', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='expedientes.actividadexpediente')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.expedientemovilidad')),
            ],
            options={
                'verbose_name': 'Documento del expediente',
                'verbose_name_plural': 'Documentos del expediente',
                'ordering': ['nombre', '-version'],
            },
        ),
        migrations.AddField(
            model_name='actividadexpediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='expedientes.expedientemovilidad'),
        ),
        migrations.CreateModel(
            name='HistorialExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='expedientes.expedientemovilidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial del expediente',
                'verbose_name_plural': 'Historial de expedientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='expedientemovilidad',
            constraint=models.UniqueConstraint(fields=('alumno', 'convocatoria'), name='expediente_unico_alumno_convocatoria'),
        ),
        migrations.AddConstraint(
            model_name='actividadexpediente',
            constraint=models.UniqueConstraint(fields=('expediente', 'actividad_proceso'), name='actividad_unica_por_expediente'),
        ),
    ]
